# Generated by Django 4.0.3 on 2022-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.CharField(default='2022-04-07', max_length=10),
        ),
    ]
